version: '3.8'
networks:
  todo-network:
    driver: bridge
    name: todo-network
services:
  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "3000:3000"
    networks:
      - todo-network

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "5500:5500"
    # depends_on:
    #   - backend
    networks:
      - todo-network

