# NOTE: Pipeline jobs are run on a VM in Github Actions, not in GHCR. 
# GHCR login is only needed when pulling or pushing to GHCR. 

name: Security Scan # The name in github actions UI

# Pipeline runs when there is a push to main
on:
    push:
        branches: [ main ]
    workflow_dispatch:

env:
    IMAGE_NAME_BACKEND: ry4nh0/todo-backend
    IMAGE_NAME_FRONTEND: ry4nh0/todo-frontend

jobs:
    scan-containers: # Job ID
        name: Scan Docker Images # User-friendly job name
        runs-on: ubuntu-latest 

        permissions:
            contents: read
            actions: write

        steps:
            # Step 1: Check out the code repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Build backend Docker image
            - name: Build backend image
              run: |
                docker build -t ghcr.io/${{ env.IMAGE_NAME_BACKEND }}:latest ./backend

            # Step 3: Build frontend Docker image
            - name: Build frontend image
              run: |
                docker build -t ghcr.io/${{ env.IMAGE_NAME_FRONTEND }}:latest ./frontend
            
            # Step 4: Scan backend image with Trivy
            - name: Scan backend image
              uses: aquasecurity/trivy-action@0.31.0
              with:
                image-ref: ${{ env.IMAGE_NAME_BACKEND }}
                format: table
                output: backend-report.txt

            # Step 5: Scan frontend image with Trivy
            - name: Scan frontend image
              uses: aquasecurity/trivy-action@0.31.0
              with:
                image-ref: ${{ env.IMAGE_NAME_FRONTEND }}
                format: table
                output: frontend-report.txt

            # Step 6: Upload scan reports as GitHub artifacts
            - name: Upload scan reports
              uses: actions/upload-artifact@v4
              with:
                name: trivy-scan-reports
                path: |
                  backend-report.txt
                  frontend-report.txt

            - name: Trigger build-and-push workflow
              uses: peter-evans/repository-dispatch@v2
              with: 
                token: ${{ secrets.DEVSECOPS_TODO }}
                event-type: trigger-build-push